runs:
  using: "composite"
  steps:
    - run: sudo ${{ github.action_path }}/dependencies.sh
      shell: bash
    - run: sudo ${{ github.action_path }}/devpool.sh
      shell: bash
    - run: sudo mkdir -p /etc/containerd
      shell: bash
    - run: sudo cp ${{ github.action_path }}/containerd.conf /etc/containerd/config.toml
      shell: bash
    - run: sudo containerd --config /etc/containerd/config.toml &
      shell: bash
