runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      run: sudo ${{ github.action_path }}/dependencies.sh
      shell: bash
    - name: Configure thin-pool
      run: |
        sudo ${{ github.action_path }}/devpool.sh
        sudo dmsetup ls
      shell: bash
    - name: Configure containerd
      run: |
        sudo mkdir -p /etc/containerd
        sudo mkdir -p /var/lib/containerd/snapshotter/devmapper
        sudo cp ${{ github.action_path }}/containerd.toml /etc/containerd/config.toml
      shell: bash
    - name: Start containerd
      run: sudo containerd --config /etc/containerd/config.toml &
      shell: bash
