name: Test
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: devmapper-containerd-action
      - name: Containerd and devmapper
        uses: yitsushi/devmapper-containerd-action@main
      - name: Check
        run: |
          sudo ctr --address=/run/containerd/containerd.sock --debug images ls
          sudo ctr --address=/run/containerd/containerd.sock --debug snapshots ls
          sudo ctr --address=/run/containerd/containerd.sock --debug snapshots --snapshotter=devmapper ls
