name: Test
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: devmapper-containerd-action
      - name: Containerd and devmapper
        uses: yitsushi/devmapper-containerd-action@main
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Check
        run: |
          sudo ctr --debug plugin ls
          sudo ctr --debug images ls
          sudo ctr --debug snapshots ls
          sudo ctr --debug snapshots --snapshotter=devmapper ls
